### ISSUE TITLE
Gateway.exe giving odd errors

### ISSUE THREAD

**Issue by cameronphillips** [MSOpenTech/connectthedots#172]
I am running the gateway.exe from my windows 8.1 machine and implementing the example given for the Sound Meter, replacing the actual data with dummy data to be sent over the socket. I am getting the following errors:

2015-06-03 10:55:16.8137 ERROR Error on lock: {"ClassName":"System.AggregateException","Message":"One or more errors occurred.","Data":null,"InnerException":{"NativeErrorCode":11001,"ClassName":"System.Net.Sockets.SocketException","Message":"No such host is known","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at System.Net.Dns.GetAddrInfo(String name)\r\n   at System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6)\r\n   at System.Net.Dns.GetHostEntry(String hostNameOrAddress)\r\n   at Amqp.TcpTransport.<ConnectAsync>d__5.MoveNext()","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"8\nGetAddrInfo\nSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nSystem.Net.Dns\nSystem.Net.IPHostEntry GetAddrInfo(System.String)","HResult":-2147467259,"Source":"System","WatsonBuckets":null},"HelpURL":null,"StackTraceString":"   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\r\n   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)\r\n   at System.Threading.Tasks.Task.Wait()\r\n   at Amqp.TcpTransport.Connect(Connection connection, Address address, Boolean noVerification)\r\n   at Amqp.Connection.Connect(SaslProfile saslProfile, Open open)\r\n   at Amqp.Connection..ctor(Address address, SaslProfile saslProfile, Open open, OnOpened onOpened)\r\n   at Amqp.Connection..ctor(Address address)\r\n   at Microsoft.ConnectTheDots.Gateway.AMQPSender`1.ReliableSender.EstablishSender() in c:\\Users\\Cameron\\Desktop\\connectthedots-master\\Devices\\Gateways\\GatewayService\\Gateway\\Utils\\MessageSender\\AMQPSender.cs:line 129","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"8\nThrowIfExceptional\nmscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nSystem.Threading.Tasks.Task\nVoid ThrowIfExceptional(Boolean)","HResult":-2146233088,"Source":"mscorlib","WatsonBuckets":null,"InnerExceptions":[{"NativeErrorCode":11001,"ClassName":"System.Net.Sockets.SocketException","Message":"No such host is known","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at System.Net.Dns.GetAddrInfo(String name)\r\n   at System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6)\r\n   at System.Net.Dns.GetHostEntry(String hostNameOrAddress)\r\n   at Amqp.TcpTransport.<ConnectAsync>d__5.MoveNext()","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"8\nGetAddrInfo\nSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nSystem.Net.Dns\nSystem.Net.IPHostEntry GetAddrInfo(System.String)","HResult":-2147467259,"Source":"System","WatsonBuckets":null}]}
2015-06-03 10:55:16.8414 ERROR Exception on sendObject reference not set to an instance of an object.
2015-06-03 10:55:16.8999 ERROR Error on lock: {"ClassName":"System.AggregateException","Message":"One or more errors occurred.","Data":null,"InnerException":{"NativeErrorCode":11001,"ClassName":"System.Net.Sockets.SocketException","Message":"No such host is known","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at System.Net.Dns.GetAddrInfo(String name)\r\n   at System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6)\r\n   at System.Net.Dns.GetHostEntry(String hostNameOrAddress)\r\n   at Amqp.TcpTransport.<ConnectAsync>d__5.MoveNext()","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"8\nGetAddrInfo\nSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nSystem.Net.Dns\nSystem.Net.IPHostEntry GetAddrInfo(System.String)","HResult":-2147467259,"Source":"System","WatsonBuckets":null},"HelpURL":null,"StackTraceString":"   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\r\n   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)\r\n   at System.Threading.Tasks.Task.Wait()\r\n   at Amqp.TcpTransport.Connect(Connection connection, Address address, Boolean noVerification)\r\n   at Amqp.Connection.Connect(SaslProfile saslProfile, Open open)\r\n   at Amqp.Connection..ctor(Address address, SaslProfile saslProfile, Open open, OnOpened onOpened)\r\n   at Amqp.Connection..ctor(Address address)\r\n   at Microsoft.ConnectTheDots.Gateway.AMQPSender`1.ReliableSender.EstablishSender() in c:\\Users\\Cameron\\Desktop\\connectthedots-master\\Devices\\Gateways\\GatewayService\\Gateway\\Utils\\MessageSender\\AMQPSender.cs:line 129","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"8\nThrowIfExceptional\nmscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nSystem.Threading.Tasks.Task\nVoid ThrowIfExceptional(Boolean)","HResult":-2146233088,"Source":"mscorlib","WatsonBuckets":null,"InnerExceptions":[{"NativeErrorCode":11001,"ClassName":"System.Net.Sockets.SocketException","Message":"No such host is known","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at System.Net.Dns.GetAddrInfo(String name)\r\n   at System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6)\r\n   at System.Net.Dns.GetHostEntry(String hostNameOrAddress)\r\n   at Amqp.TcpTransport.<ConnectAsync>d__5.MoveNext()","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"8\nGetAddrInfo\nSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nSystem.Net.Dns\nSystem.Net.IPHostEntry GetAddrInfo(System.String)","HResult":-2147467259,"Source":"System","WatsonBuckets":null}]}
2015-06-03 10:55:16.9280 ERROR Exception on sendObject reference not set to an instance of an object.
2015-06-03 10:55:16.9553 ERROR Exception in task:    at Microsoft.ConnectTheDots.Gateway.AMQPSender`1.SendAmqpMessage(Message m) in c:\Users\Cameron\Desktop\connectthedots-master\Devices\Gateways\GatewayService\Gateway\Utils\MessageSender\AMQPSender.cs:line 355
   at Microsoft.ConnectTheDots.Gateway.AMQPSender`1.<PrepareAndSend>b__0(Message m) in c:\Users\Cameron\Desktop\connectthedots-master\Devices\Gateways\GatewayService\Gateway\Utils\MessageSender\AMQPSender.cs:line 324
   at Microsoft.ConnectTheDots.Common.SafeAction`1.SafeInvoke(TParam obj) in c:\Users\Cameron\Desktop\connectthedots-master\Devices\Gateways\GatewayService\Common\SafeAction.cs:line 48
2015-06-03 10:55:16.9553 ERROR Message in task: Object reference not set to an instance of an object.

On my dummy code, it is showing that the socket successfully connects and is sending the JSON data to the socket. What gives? Why is this not properly running on Windows?

**Comment by dinarisio** [comment]
' "Message":"No such host is known" ' - it looks like the amqp connection string is wrong, could you please check?

**Comment by spyrossak** [comment]
Closed due to lack of activity. Please re-open if necessary.
